services:
  - type: web
    name: secretsanta-v2
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: RESET_DATA_ON_START
        value: "true"
    healthCheckPath: /

